### ISSUE TITLE
Add permissions to GitHub workflows

### ISSUE THREAD

**Issue by abelsiqueira** [abelsiqueira/BestieTemplate.jl#131]
Such as

```yaml
    permissions:
      contents: write
      pull-requests: read
      statuses: write
```

Taken from https://documenter.juliadocs.org/stable/man/hosting/#GitHub-Actions
