### ISSUE TITLE
Consider making lychee.toml a hidden file

### ISSUE THREAD

**Issue by moble** [abelsiqueira/BestieTemplate.jl#388]
### Description

I always find config files in the base directory a little distracting and confusing.  The saving grace is that at least when they are hidden files, they are either not shown or collected together so I can easily skip past them.  Currently, lychee.toml violates this so that — for example — if I'm looking for my README.md or Project.toml file, I have to visually sort out lychee.toml.

It would be easy enough to just create it as .lychee.toml, and then just add the arg to `Lint.yml` to find it:
```
            - name: Link Checker
              id: lychee
              uses: lycheeverse/lychee-action@v1
              with:
                  fail: true
                  args: --config '.lychee.toml'
```
